package com.unicom.busi.dao.mapper;

import com.unicom.busi.entity.SysUser;

import java.util.List;

public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon May 15 13:13:19 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon May 15 13:13:19 CST 2017
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon May 15 13:13:19 CST 2017
     */
    SysUser selectByPrimaryKey(Integer id);
    
    SysUser getUserByName(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon May 15 13:13:19 CST 2017
     */
    List<SysUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon May 15 13:13:19 CST 2017
     */
    int updateByPrimaryKey(SysUser record);

    List<SysUser> getUsersByName(String username);
}